### ISSUE TITLE
Can't play any music

### ISSUE THREAD

**Issue by space192** [iiFir3z/Apple-Music-Electron#10]
whenever I click on a song I wanna hear I get this error:
Failed to load because no supported source was found.

**Comment by iiFir3z** [comment]
This bug is due to Apple's new authentication. Try signing out in the client and signing back in. Im currently working on a new fix for this bug.

**Comment by CandenizErdal** [comment]
I get this error +1

**Comment by space192** [comment]
Issue still there even after 1.5.5 (i'm located in france if that matters)
so this Issue isn't solved yet
but keep up with the great work guys :D

**Comment by iiFir3z** [comment]
v1.5.6 should fix your issue now. Let me know how this goes and if it works again so I can close this issue.

**Comment by space192** [comment]
yeah it actually fixed the issue ! thanks so much :D

**Comment by GabeAC** [comment]
Hate to bump this after so long but I'm experiencing the same issue with 1.5.8

**Comment by cryptofyre** [comment]
What operating system are you running and from what package are you using AME with? Packages like the AppImage do tend to bug out with Widevine so if possible try installing the standard packages.
