### ISSUE TITLE
[Feature Request] Ability to minimze app to system tray

### ISSUE THREAD

**Issue by arya1106** [iiFir3z/Apple-Music-Electron#12]
I'd like the ability to click the X button to minimize the player to the system tray while still having playback continue. Something similar to Deezer's electron client. Thanks for creating this!

**Comment by devilAPI** [comment]
nice idea, i like it!

**Comment by arya1106** [comment]
Ended up implementing this feature myself, opened a PR.

**Comment by arya1106** [comment]
PR is merged, closing the issue
