### ISSUE TITLE
can't launch app [1.5.3]

### ISSUE THREAD

**Issue by space192** [iiFir3z/Apple-Music-Electron#17]
![image](https://user-images.githubusercontent.com/44359684/107382811-989c2f80-6af0-11eb-9726-8b5cae6463be.png)
the software just show a white window :/

**Comment by arya1106** [comment]
This is because the latest release has an issue, with the check implemented in #15  (see #18 for details)  I'd recommend downgrading to 1.5.2 until a new version is released. If you still want the build with the tray icon from #14  and the new title bar from #18, I can send you a build for your platform.

**Comment by space192** [comment]
Sorry I don't have anything related to JS installed on my computer yet (I will learn one-day xD) so for now, I will downgrade to 1.5.2 but thanks for your time and effort to develop this project !!

**Comment by arya1106** [comment]
Oh no, no need for you to install anything, I was just offering to build an installable version of the app for you. And thank you, but most of the work here is done by @iiFir3z 😄

**Comment by devilAPI** [comment]
Oh im sorry, i kinda messed up the code there, my fix for my code is here: #19

**Comment by space192** [comment]
perfect the display works now !
![image](https://user-images.githubusercontent.com/44359684/107482389-e57b1700-6b7f-11eb-844c-1c75cd8c5cc2.png)
still the bug where I can't play any music but I already created the issue #10 but the program looks nice now :D

**Comment by devilAPI** [comment]
Close issue?

**Comment by space192** [comment]
Problem solved thanks guys !
