### ISSUE TITLE
Failed to install Widevine component

### ISSUE THREAD

**Issue by ArthurRyan0803** [iiFir3z/Apple-Music-Electron#25]
![image](https://user-images.githubusercontent.com/38326748/108871507-308f3280-7634-11eb-9155-41286831dd16.png)

**Comment by iiFir3z** [comment]
I am unsure if v1.5.6 fixed this issue but feel free to confirm if it does.

**Comment by ArthurRyan0803** [comment]
It's solved. Windows defender blocks installation.
