### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by babiloof** [iiFir3z/Apple-Music-Electron#3]
When i press play i get error "Failed to load because no supported source was found."

**Comment by babiloof** [comment]
Tryed logging out and in and now i get a "CONTENT_EQUIVALENT" message instead.

**Comment by babiloof** [comment]
Nvm, got it working, reinstalled nodejs with newest version, and ran the app in the dist folder instead of running with yarn start, new to this...
Loving the app, really fast compared to alternatives

**Comment by JackTAZz** [comment]
hey yo could you explain me how you fixed it

**Comment by babiloof** [comment]
what worked for me when i had the same error was opening the Apple-Music-Electron\dist\Apple Music Setup 1.5.0.exe after running the yarn install & yarn dist commands

**Comment by babiloof** [comment]
> 
> 
> hey yo could you explain me how you fixed it

what worked for me when i had the same error was opening the Apple-Music-Electron\dist\Apple Music Setup 1.5.0.exe after running the yarn install & yarn dist commands
