### ISSUE TITLE
Repeat 1 track not working

### ISSUE THREAD

**Issue by babiloof** [iiFir3z/Apple-Music-Electron#4]
The repeat 1 track only feature dosent seem to work, when you click the repeat button so it gets red and a 1 above.
It plays the track then stops after.

**Comment by iiFir3z** [comment]
Hmm. This may be part of the way Apple handles audio with DRM and direct streams. Ill check it out same with the GPU bug.

**Comment by iiFir3z** [comment]
This feature should be working now! Please do let me know if it continues. (v1.5.0)
