### ISSUE TITLE
High GPU usage for playback icon

### ISSUE THREAD

**Issue by babiloof** [iiFir3z/Apple-Music-Electron#5]
Theres high gpu usage for the playback icon, the one that shows up when youve pressed play (on the same spot as the play button) when you are in a playlist or album etc.
If you hover it so it becomes a pause button the GPU usage goes down to almost zero.
This issue seems to be on the official web aswell, maby it can be fixed in this app?

**Comment by iiFir3z** [comment]
Weird bug. Ill check it out and see what I can do about it.

**Comment by iiFir3z** [comment]
1.5.0 has fixed all performance bugs and also added Discord RPC support! Thanks for notifying me of the bugs!
