### ISSUE TITLE
You might find this useful

### ISSUE THREAD

**Issue by JarekToro** [iiFir3z/Apple-Music-Electron#6]
I cloned your repo for my personal project. I ended up changing to many things and removing discord so I didnt want to create a pull request. But I created a simple way to talk to Apple's MusicKit and get all of the current Song metadata. As well as play pause skip controls.

You may want to integrate some of it into this project;
 
https://github.com/JarekToro/Apple-Music-Mpris

**Comment by iiFir3z** [comment]
This helps a LOT! Ill try and integrate it with my other features.

**Comment by iiFir3z** [comment]
Merged and changed up everything to fit all your changes! Thanks again!

**Comment by ColdtQ** [comment]
Your functions are in ES5, pls update them ur triggering me
