### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by JackTAZz** [iiFir3z/Apple-Music-Electron#8]
when I try to play music I get the message: Failed to load because no supported source was found

**Comment by iiFir3z** [comment]
Mind telling me what OS and Audio system your using? ex. (OS: Linux, Audio: PulseAudio)

**Comment by iiFir3z** [comment]
I have just launched 1.5.2 please let me know if that fixes your issue!

**Comment by JackTAZz** [comment]
i am on windows 10 and im using realtek

**Comment by JackTAZz** [comment]
1.5.2 didnt fixed it

**Comment by JackTAZz** [comment]
![image](https://user-images.githubusercontent.com/71618372/102176296-2223de00-3e6f-11eb-895e-7e052c4e7276.png)

**Comment by babiloof** [comment]
did you install the app with the "Apple Music Setup" file in the dist folder after running the yarn install & yarn dist commands?

**Comment by JackTAZz** [comment]
> did you install the app with the "Apple Music Setup" file in the dist folder after running the yarn install & yarn dist commands?

no i didnt how do we do ?

**Comment by parmvirsingh** [comment]
Installed via the exe release.
Same error:
"Failed to load because no supported source was found"

**Comment by ronathon123** [comment]
Same here. I'm on Windows 10 and I installed with yarn. When played from a playlist, this error is given. When I play some random song from browse, it plays 1:30 of each song only. Looks like a preview or demo of the song.

**Comment by ronathon123** [comment]
Just fixed it I think. First, I reinstalled node.js as babiloof did in his issue thread, and installed using yarn. I installed node.js version 14.15.4 LTS. I think reinstalling node.js was the key though, since I tried installing with yarn instead of the .exe file before and it didn't fix it.

**Comment by parmvirsingh** [comment]
> Just fixed it I think. First, I reinstalled node.js as babiloof did in his issue thread, and installed using yarn. I installed node.js version 14.15.4 LTS. I think reinstalling node.js was the key though, since I tried installing with yarn instead of the .exe file before and it didn't fix it.

I'll try this out in a bit and see if it fixes the issue for me as well.

**Comment by parmvirsingh** [comment]
> > Just fixed it I think. First, I reinstalled node.js as babiloof did in his issue thread, and installed using yarn. I installed node.js version 14.15.4 LTS. I think reinstalling node.js was the key though, since I tried installing with yarn instead of the .exe file before and it didn't fix it.
> 
> I'll try this out in a bit and see if it fixes the issue for me as well.

Installed node.js 14.15.4. Installed using Yarn and and via the exe same issue.

**Comment by JackTAZz** [comment]
@iiFir3z i think the problem i have just happened on the browser. After I refreshed the problem was fix. Maybe you could add a refresh button or something like that

**Comment by parmvirsingh** [comment]
> > > Just fixed it I think. First, I reinstalled node.js as babiloof did in his issue thread, and installed using yarn. I installed node.js version 14.15.4 LTS. I think reinstalling node.js was the key though, since I tried installing with yarn instead of the .exe file before and it didn't fix it.
> > 
> > 
> > I'll try this out in a bit and see if it fixes the issue for me as well.
> 
> Installed node.js 14.15.4. Installed using Yarn and and via the exe same issue.

Interesting fix for me. After digging around I signed out of my Apple Music on iTunes. No issues since.

**Comment by iiFir3z** [comment]
If you are still having issues after the v1.5.6 release please let me know.

**Comment by JackTAZz** [comment]
With the v.1.5.6 everything works
